// In-memory sample data for the MARG / NSFDC Government Portal demo.
// Nothing here hits a real database or external API — resets whenever the server restarts.

export const schemes = [
  {
    id: "sch_mfs",
    name: "Micro Finance Scheme (MFS)",
    code: "MFS",
    description:
      "Small-ticket concessional loans for individual entrepreneurs and micro-enterprises run by SC beneficiaries.",
    status: "published", // draft | published | deprecated
    version: 3,
    minIncome: 0,
    maxIncome: 500000,
    minProjectCost: 0,
    maxProjectCost: 140000,
    projectTypes: ["Retail", "Agriculture", "Services", "Transport"],
    interestRate: 6.5,
    govtSharePct: 90,
    beneficiarySharePct: 10,
    moratoriumMonths: 3,
    tenureMonths: 36,
    effectiveFrom: "2025-04-01",
    updatedAt: "2026-06-10T10:00:00Z",
  },
  {
    id: "sch_msy",
    name: "Mahila Samriddhi Yojana (MSY)",
    code: "MSY",
    description: "Concessional micro-loans targeted exclusively at women entrepreneurs and self-help groups from SC communities.",
    status: "published",
    version: 2,
    minIncome: 0,
    maxIncome: 500000,
    minProjectCost: 0,
    maxProjectCost: 150000,
    projectTypes: ["Retail", "Services", "Handicrafts"],
    interestRate: 5.0,
    govtSharePct: 90,
    beneficiarySharePct: 10,
    moratoriumMonths: 6,
    tenureMonths: 48,
    effectiveFrom: "2025-04-01",
    updatedAt: "2026-05-22T10:00:00Z",
  },
  {
    id: "sch_tl",
    name: "Term Loan Scheme (TL)",
    code: "TL",
    description: "Medium-to-large project financing for viable enterprise creation, expansion, and modernisation by SC beneficiaries.",
    status: "published",
    version: 4,
    minIncome: 0,
    maxIncome: 500000,
    minProjectCost: 140000,
    maxProjectCost: 5000000,
    projectTypes: ["Retail", "Agriculture", "Transport", "Manufacturing"],
    interestRate: 7.0,
    govtSharePct: 85,
    beneficiarySharePct: 15,
    moratoriumMonths: 6,
    tenureMonths: 84,
    effectiveFrom: "2025-04-01",
    updatedAt: "2026-07-01T10:00:00Z",
  },
  {
    id: "sch_edu",
    name: "Educational Loan Scheme (ELS)",
    code: "EDU",
    description: "Subsidised loans covering tuition, living expenses, and study materials for professional and technical higher education in India or abroad.",
    status: "published",
    version: 2,
    minIncome: 0,
    maxIncome: 500000,
    minProjectCost: 0,
    maxProjectCost: 4000000,
    projectTypes: ["Education"],
    interestRate: 4.0,
    govtSharePct: 100,
    beneficiarySharePct: 0,
    moratoriumMonths: 12,
    tenureMonths: 120,
    effectiveFrom: "2025-04-01",
    updatedAt: "2026-03-15T10:00:00Z",
  },
  {
    id: "sch_old_craft",
    name: "Artisan Legacy Scheme (ALS)",
    code: "ALS",
    description: "Retired legacy scheme for traditional crafts; archived for historical audit and accounting compliance.",
    status: "deprecated",
    version: 1,
    minIncome: 0,
    maxIncome: 300000,
    minProjectCost: 0,
    maxProjectCost: 100000,
    projectTypes: ["Handicrafts"],
    interestRate: 8.0,
    govtSharePct: 80,
    beneficiarySharePct: 20,
    moratoriumMonths: 3,
    tenureMonths: 24,
    effectiveFrom: "2019-01-01",
    updatedAt: "2024-01-10T10:00:00Z",
  },
];

// Pending edits awaiting a second admin's approval (maker-checker demo)
export const pendingChanges = [
  {
    id: "chg_demo_1",
    schemeId: "sch_mfs",
    proposedBy: "admin_ravi",
    proposedAt: "2026-09-02T14:30:00Z",
    changes: {
      interestRate: 6.0,
      description: "Proposed 0.5% interest concession for rural agri-allied units under MFS.",
    },
    status: "pending",
  },
];

export const auditLog = [
  {
    id: "log_1",
    actor: "admin_ravi",
    action: "PUBLISH",
    schemeId: "sch_edu",
    detail: "Published Educational Loan v2 with 4.0% p.a. concessional rate",
    timestamp: "2026-03-15T10:00:00Z",
  },
  {
    id: "log_2",
    actor: "admin_priya",
    action: "APPROVE_CHANGE",
    schemeId: "sch_tl",
    detail: "Approved project cost ceiling enhancement to ₹50,00,000 for Term Loan v4",
    timestamp: "2026-07-01T11:20:00Z",
  },
  {
    id: "log_3",
    actor: "admin_ravi",
    action: "PROPOSE_CHANGE",
    schemeId: "sch_mfs",
    detail: "Proposed reduction of MFS rate from 6.5% to 6.0% p.a. (Awaiting Checker Approval)",
    timestamp: "2026-09-02T14:30:00Z",
  },
];

// Empanelled channel partners (SCAs / PSBs / RRBs / NBFC-MFIs) across states
export const partners = [
  {
    id: "p1",
    name: "State Bank of India — Malviya Nagar Branch",
    type: "PSB",
    state: "Rajasthan",
    city: "Jaipur",
    address: "B-12, Calgiri Marg, Malviya Nagar, Jaipur, RJ 302017",
    lat: 26.8505,
    lng: 75.8115,
    npaPct: 4.2,
    quotaRemainingPct: 62,
    phone: "0141-2345001",
    email: "sbi.malviya@sbi.co.in",
  },
  {
    id: "p2",
    name: "Rajasthan SC/ST Finance Development Corp (Jaipur SCA)",
    type: "SCA",
    state: "Rajasthan",
    city: "Jaipur",
    address: "Nehru Sahkar Bhawan, 4th Floor, 22 Godam Circle, Jaipur, RJ 302005",
    lat: 26.9124,
    lng: 75.7873,
    npaPct: 3.1,
    quotaRemainingPct: 40,
    phone: "0141-2345002",
    email: "sca.jaipur@rajasthan.gov.in",
  },
  {
    id: "p3",
    name: "Punjab National Bank — C-Scheme Branch",
    type: "PSB",
    state: "Rajasthan",
    city: "Jaipur",
    address: "LIC Building, Subhash Marg, C-Scheme, Jaipur, RJ 302001",
    lat: 26.9155,
    lng: 75.8080,
    npaPct: 11.5,
    quotaRemainingPct: 5,
    phone: "0141-2345003",
    email: "pnb.cscheme@pnb.co.in",
  },
  {
    id: "p4",
    name: "Jaipur Thar Gramin Bank (RRB)",
    type: "RRB",
    state: "Rajasthan",
    city: "Jaipur",
    address: "Kisan Bhawan, Tonk Road, Jaipur, RJ 302015",
    lat: 26.8850,
    lng: 75.7550,
    npaPct: 6.7,
    quotaRemainingPct: 28,
    phone: "0141-2345004",
    email: "rrb.jaipur@jtgb.co.in",
  },
  {
    id: "p5",
    name: "Ujjivan Small Finance Bank — Vaishali Nagar",
    type: "NBFC-MFI",
    state: "Rajasthan",
    city: "Jaipur",
    address: "Plot 82, Amrapali Circle, Vaishali Nagar, Jaipur, RJ 302021",
    lat: 26.9020,
    lng: 75.7400,
    npaPct: 5.0,
    quotaRemainingPct: 75,
    phone: "0141-2345005",
    email: "ujjivan.vaishali@ujjivan.com",
  },
  {
    id: "p6",
    name: "Delhi SC Finance Development Corp (DSFDC)",
    type: "SCA",
    state: "Delhi",
    city: "New Delhi",
    address: "2, Battery Lane, Rajpur Road, Civil Lines, Delhi 110054",
    lat: 28.6739,
    lng: 77.2201,
    npaPct: 4.9,
    quotaRemainingPct: 55,
    phone: "011-23456001",
    email: "dsfdc.delhi@nic.in",
  },
  {
    id: "p7",
    name: "Canara Bank — Connaught Place Branch",
    type: "PSB",
    state: "Delhi",
    city: "New Delhi",
    address: "F-19, Outer Circle, Connaught Place, New Delhi 110001",
    lat: 28.6315,
    lng: 77.2167,
    npaPct: 3.9,
    quotaRemainingPct: 48,
    phone: "011-23456002",
    email: "canara.cp@canarabank.com",
  },
  {
    id: "p8",
    name: "Maharashtra State SC/ST Dev Corp (Mahatama Phule)",
    type: "SCA",
    state: "Maharashtra",
    city: "Mumbai",
    address: "Juhu Vile Parle Development Scheme, Mumbai, MH 400049",
    lat: 19.1030,
    lng: 72.8270,
    npaPct: 4.5,
    quotaRemainingPct: 65,
    phone: "022-26189001",
    email: "mpbcdc.mumbai@maharashtra.gov.in",
  },
  {
    id: "p9",
    name: "Bank of India — Fort Branch",
    type: "PSB",
    state: "Maharashtra",
    city: "Mumbai",
    address: "70/80 MG Road, Fort, Mumbai, MH 400001",
    lat: 18.9322,
    lng: 72.8335,
    npaPct: 4.8,
    quotaRemainingPct: 58,
    phone: "022-22678000",
    email: "boi.fort@bankofindia.co.in",
  },
  {
    id: "p10",
    name: "Uttar Pradesh SC Finance & Dev Corp (SCA)",
    type: "Uttar Pradesh",
    city: "Lucknow",
    address: "Babu Bhawan, Vidhan Sabha Marg, Lucknow, UP 226001",
    lat: 26.8467,
    lng: 80.9462,
    npaPct: 5.4,
    quotaRemainingPct: 50,
    phone: "0522-2234001",
    email: "upscfdc.lko@up.gov.in",
  },
];

export const otpStore = new Map(); // mobile -> { otp, expiresAt }

// Pre-populated demo applications for immediate tracking tests
export const applications = [
  {
    id: "app_demo_01",
    trackingId: "MOSJE-582914",
    mobile: "9876543210",
    schemeId: "sch_msy",
    schemeSnapshot: {
      name: "Mahila Samriddhi Yojana (MSY)",
      code: "MSY",
      interestRate: 5.0,
      govtSharePct: 90,
      beneficiarySharePct: 10,
      moratoriumMonths: 6,
      tenureMonths: 48,
    },
    formData: {
      applicantName: "Sunita Devi",
      annualIncome: 180000,
      projectCost: 120000,
      loanAmount: 108000,
      projectType: "Handicrafts & Tailoring",
      partnerId: "p2",
      partnerName: "Rajasthan SC/ST Finance Corp - Jaipur SCA",
    },
    stage: 3,
    stageName: "Forwarded to Channel Partner for Field Appraisal",
    status: "processing",
    submittedAt: "2026-08-25T11:15:00Z",
    history: [
      { step: 1, title: "Application & e-KYC Submitted", date: "25 Aug 2026, 11:15 AM", note: "Aadhaar verified via OTP" },
      { step: 2, title: "District Nodal Scrutiny Completed", date: "28 Aug 2026, 03:40 PM", note: "Caste and income certificate verified" },
      { step: 3, title: "Forwarded to Channel Partner", date: "01 Sep 2026, 10:20 AM", note: "Assigned to Jaipur SCA for site verification" },
    ],
  },
  {
    id: "app_demo_02",
    trackingId: "MOSJE-102938",
    mobile: "9123456789",
    schemeId: "sch_edu",
    schemeSnapshot: {
      name: "Educational Loan Scheme (ELS)",
      code: "EDU",
      interestRate: 4.0,
      govtSharePct: 100,
      beneficiarySharePct: 0,
      moratoriumMonths: 12,
      tenureMonths: 120,
    },
    formData: {
      applicantName: "Rohan Prakash Kamble",
      annualIncome: 240000,
      projectCost: 850000,
      loanAmount: 850000,
      projectType: "Education (B.Tech Degree)",
      partnerId: "p1",
      partnerName: "State Bank of India — Malviya Nagar",
    },
    stage: 4,
    stageName: "Loan Sanctioned & Disbursed",
    status: "sanctioned",
    submittedAt: "2026-07-10T09:30:00Z",
    history: [
      { step: 1, title: "Application & e-KYC Submitted", date: "10 Jul 2026, 09:30 AM", note: "Documents uploaded" },
      { step: 2, title: "College Admission Letter Verified", date: "14 Jul 2026, 02:15 PM", note: "Tuition schedule approved" },
      { step: 3, title: "Forwarded to SBI Malviya Nagar", date: "18 Jul 2026, 11:00 AM", note: "Appraisal report positive" },
      { step: 4, title: "Sanction Letter Issued & Disbursed", date: "26 Jul 2026, 04:45 PM", note: "First semester fee transferred to institute" },
    ],
  },
];

export const grievances = [
  {
    ticketId: "GRV-2026-7821",
    name: "Mukesh B.",
    mobile: "9823012345",
    trackingId: "MOSJE-582914",
    category: "Status Delay",
    description: "Inquiry regarding field inspection date from Jaipur SCA.",
    status: "Resolved",
    submittedAt: "2026-08-30T15:00:00Z",
    response: "Field inspection scheduled for 06 Sep 2026 by Nodal Officer.",
  },
];
